company/urls.py
from django.urls import path

from .views import (
    CompanyFormView,
    CompanyView,
    LawsuitsList,
    NewsList,
    ReportsList,
    change_rate,
    favorite_company,
    SuggestionSucessView,
)

app_name = "company"
urlpatterns = [
    path("<int:pk>/", CompanyView.as_view(), name="company"),
    path("<int:company_id>/change", change_rate, name="change"),
    path("<int:company_id>/favoritar", favorite_company, name="favorite"),
    path("<int:company_id>/noticias", NewsList.as_view(), name="news"),
    path("<int:company_id>/processos", LawsuitsList.as_view(), name="lawsuits"),
    path("<int:company_id>/denuncias", ReportsList.as_view(), name="reports"),
    path("suggest", CompanyFormView.as_view(), name="suggest"),
    path(
        "suggest/confirmation", SuggestionSucessView.as_view(), name="suggest_success"
    ),
]

infos/urls.py
from django.urls import path

from . import views

app_name = "infos"
urlpatterns = [
    path("report/confirmation/", views.ReportSucessView.as_view(), name="success"),
    path("report/", views.ReportFormView.as_view(), name="report"),
    path("denuncia/<int:pk>", views.ReportStrategy.as_view(), name="reportdetail"),
    path("noticia/<int:pk>", views.NewsStrategy.as_view(), name="newsdetail"),
    path("processo/<int:pk>", views.LawsuitStrategy.as_view(), name="lawsuitdetail"),
]

pensenisso/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path
from home.views import HomeView

def about_us(request):
    return render(request, "global/about_us.html")
def privacy_policy(request):
    return render(request, "global/privacy_policy.html")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("about_us", about_us, name="about_us"),
    path("privacy_policy", privacy_policy, name="privacy_policy"),
    path("empresas/", include("company.urls")),
    path("info/", include("infos.urls", namespace="infos")),
    path("users/", include("user.urls", namespace="user")),
    path("search/", include("search.urls", namespace="search")),
    path("comparator/", include("comparator.urls", namespace="comparator")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    ChangePassword,
    EditProfile,
    ListaUsuarios,
    PendingReportList,
    Register,
    ReportValidation,
    UserPage,
    account_redirect,
    CompanyValidation,
    PendingSuggestionList
)

app_name = "user"

urlpatterns = [
    path("", Register.as_view(), name="register"),
    path("profile/<int:pk>", UserPage.as_view(), name="profile"),
    path("usuarios/", ListaUsuarios.as_view(), name="listausuario"),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="logout.html"), name="logout"),
    path(
        "moderation/pending_reports/",
        PendingReportList.as_view(),
        name="pendingreports",
    ),
    path(
        "moderation/pending_reports/<int:pk>",
        ReportValidation.as_view(),
        name="reportvalidation",
    ),
    path(
        "profile/<int:pk>/edit/password",
        ChangePassword.as_view(),
        name="changepassword",
    ),
    path("profile/<int:pk>/edit/", EditProfile.as_view(), name="editprofile"),
    path("profile", account_redirect, name="account-redirect"),
    path(
        "moderation/pending_suggestions/",
        PendingSuggestionList.as_view(),
        name="pendingsuggestions",
    ),
    path(
        "moderation/pending_suggestions/<int:pk>",
        CompanyValidation.as_view(),
        name="suggestionvalidation",
    ),
]

infos/models.py
from django.db import models


class InfoBase(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self) -> str:
        return self.title

    class Meta:
        abstract = True


class Report(InfoBase):
    company = models.ForeignKey(
        "company.Company", on_delete=models.CASCADE, related_name="reports"
    )
    category = models.ForeignKey("ReportCategory", on_delete=models.SET_NULL, null=True)
    links = models.TextField()
    user = models.ForeignKey(
        "user.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports_sent",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=20,
        choices=[("RE", "Recusado"), ("NV", "Não verificado"), ("AP", "Aprovado")],
        default="NV",
    )
    gravity = models.CharField(
        max_length=20,
        choices=[("1", "Leve"), ("2", "Moderada"), ("3", "Grave"), ("4", "Gravíssima")],
        default="1",
    )
    date = models.DateField(default="1970-01-01")
    feedback = models.TextField(blank=True)


class ReportCategory(models.Model):
    name = models.CharField(max_length=100)
    formatted_name = models.CharField(max_length=100, default="Categoria")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Report categories"


class Lawsuit(InfoBase):
    company = models.ForeignKey(
        "company.Company", on_delete=models.CASCADE, related_name="lawsuits"
    )
    source = models.URLField()
    start_year = models.PositiveSmallIntegerField()
    resolution_year = models.PositiveSmallIntegerField(null=True, blank=True)


class News(InfoBase):
    company = models.ForeignKey(
        "company.Company", on_delete=models.CASCADE, related_name="news"
    )
    author = models.CharField(max_length=50)
    date = models.DateField()
    image = models.ImageField(upload_to="news_banners")

    class Meta:
        verbose_name_plural = "News"

infos/forms.py
from django import forms
from django.forms import widgets

from company.models import Company

from .fields import CompanyModelChoiceField, ReportCategoryModelChoiceField
from .models import ReportCategory
import datetime

STRING_COMPANY = "Empresa envolvida:"
STRING_EMPTY_COMPANY = "Selecione uma empresa"
STRING_LINK = "Links de evidências:"
STRING_DESCRIPTION = "Descrição da denúncia:"
STRING_CONTACT = "Podemos entrar em contato para obter mais informações?"
STRING_CATEGORY = "Escolha uma categoria de denúncia"
STRING_EMPTY_CATEGORY = "Selecione uma categoria"
STRING_DATE = "Data da ocorrência:"

def valid_date(value):
    if value > datetime.date.today():
        raise forms.ValidationError("A data não pode ser maior que a data atual!")
    elif value < datetime.date(1970, 1, 1):
        raise forms.ValidationError("A data não pode ser menor que 01/01/1970!")
    return value

class ReportForm(forms.Form):
    template_name = "form/report_form_template.html"

    company = CompanyModelChoiceField(
        queryset=Company.objects.all(),
        label=STRING_COMPANY,
        empty_label=STRING_EMPTY_COMPANY,
    )
    category = ReportCategoryModelChoiceField(
        queryset=ReportCategory.objects.all(),
        label=STRING_CATEGORY,
        empty_label=STRING_EMPTY_CATEGORY,
    )
    link = forms.URLField(label=STRING_LINK)
    description = forms.CharField(
        label=STRING_DESCRIPTION,
        max_length=300,
        widget=forms.Textarea(attrs={"cols": "45", "rows": "8"}),
    )
    date = forms.DateField(
        label=STRING_DATE, widget=widgets.DateInput(attrs={"type": "date"}), validators=[valid_date],
    )
    contact_permission = forms.BooleanField(
        label=STRING_CONTACT, required=False, initial=False
    )

infos/views.py
from typing import Any

from django.contrib.auth import get_user
from django.http import HttpResponse
from django.utils import timezone
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import FormView

from . import forms
from .models import Lawsuit, News, Report


class ReportSucessView(TemplateView):
    template_name = "confirmation.html"


class ReportFormView(FormView):
    template_name = "report.html"
    form_class = forms.ReportForm
    success_url = "confirmation/"

    def form_valid(self, form: forms.ReportForm) -> HttpResponse:
        data = form.cleaned_data
        current_date = timezone.now().isoformat(timespec="seconds")
        current_user = get_user(self.request)

        generated_title = (
            f"{current_date}-{data['company'].name}-{data['category'].name}"
        )

        report = Report(
            title=generated_title,
            content=data["description"],
            category=data["category"],
            links=data["link"],
            company=data["company"],
            user=current_user if current_user.is_authenticated else None,
            date=data["date"],
        )

        report.save()
        return super().form_valid(form)


class InfoStrategy(DetailView):
    info_type = ""

    def get_context_data(self, **kwargs: Any) -> "dict[str, Any]":
        context = super().get_context_data(**kwargs)
        context.update(
            {"info_type": self.info_type, "info_title": self.get_info_title()}
        )
        return context

    def get_info_title(self):
        pass


class ReportStrategy(InfoStrategy):
    model = Report
    info_type = "Denúncia"
    template_name = "report_details.html"

    def get_info_title(self):
        return self.get_object().category

    def get_context_data(self, **kwargs: Any) -> "dict[str, Any]":
        context = super().get_context_data(**kwargs)
        context["object"].links = context.get("object").links.split("\r\n")
        return context


class NewsStrategy(InfoStrategy):
    model = News
    info_type = "Notícia"
    template_name = "news_details.html"

    def get_info_title(self):
        return self.get_object().title


class LawsuitStrategy(InfoStrategy):
    model = Lawsuit
    info_type = "Processo"
    template_name = "lawsuit_details.html"

    def get_info_title(self):
        return self.get_object().title

infos/templates/confirmation.html
{% extends "global/base.html" %} {% block title %} - Denúncia Enviada {% endblock %}
{% block content %}

<div class="flex flex-column justify-center items-center bg-red-400 text-white w-full h-10 text-center my-6">
    <h1 class="text-2xl font-bold">Denúncia enviada!</h1>
</div>

<p>
    Obrigado por submeter sua denúncia! Sua ajuda é muito importante para nós!
</p>
<a href="{% url 'infos:report' %}" class="underline text-blue-500 visited:text-purple-600 mt-2.5">Enviar outra denúncia</a>
{% endblock content %}

infos/templates/explorador.html
{% extends "global/base.html" %}
{% block title %} - Explorador {% endblock %}
{% block content %}
    <ul>
    {% for company in companies %}
    <li><a href="{% url 'infos:company' company.id %}" class="empresa">{{ company.name }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

infos/templates/info_details.html
{% extends "global/base.html" %}

{% block title %}
- {{ info_title }}
{% endblock %}

{% block content %}
<div class="bg-blue-600 text-white w-full text-center my-6">
    <h1 class="text-2xl font-bold">{{ info_type }}</h1>
    <p class="text-sm font-semibold">{{ object.company }}</p>
</div>

<h1 class="text-3xl font-bold w-11/12">{{ info_title }}</h1>

<ul class="w-11/12 list-disc list-inside my-1">{% block metadata %}{% endblock %}</ul>

<div class="divider"></div>

<h2 class="text-2xl font-bold w-11/12 my-1">Detalhes</h2>
<p class="w-11/12 text-justify leading-tight">{{ object.content|linebreaksbr }}</p>

{% block extra %} {% endblock %}
{% endblock %}

infos/templates/lawsuit_details.html
{% extends "info_details.html" %}
{% load info_extras %}

{% block metadata %}
<li><strong>Ano de Início: </strong>{{ object.start_year }}</li>
{% if object.resolution_year %}
<li><strong>Ano de Resolução: </strong>{{ object.resolution_year }}</li>
{% endif %}
<li><strong>Fonte: </strong>{{ object.source|urlize|url_fix }}</li>
{% endblock %}

infos/templates/news_details.html
{% extends "info_details.html" %}

{% block metadata %}
<li>Data: {{ object.date|date:"d/m/Y" }}</li>
<li>Por {{ object.author }}</li>
{% endblock %}

infos/templates/report.html
{% extends "report_template.html" %}
{% load crispy_forms_tags %}

{% block title %}
- Denuncie
{% endblock %}

{% block form_content %}
    <form action="/info/report/" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="flex flex-nowrap justify-center space-x-10 mt-2 w-full">
            <input class="text-white my-3 btn w-full bg-red-500 hover:bg-red-600" type="submit" value="Enviar Denúncia">
        </div>
    </form>
{% endblock %}

infos/templates/report_details.html
{% extends "info_details.html" %}
{% load info_extras %}

{% block metadata %}
<li><strong>Data: </strong>{{ object.date|date:"d/m/Y" }}</li>
<li>
    <strong>Gravidade: </strong>
    {% if report.gravity == "1" %}
    <span class="text-lime-600">Leve</span>
    {% elif report.gravity == "2" %}
    <span class="text-yellow-500">Moderada</span>
    {% elif report.gravity == "3" %}
    <span class="text-orange-600">Grave</span>
    {% else %}
    <span class="text-red-700">Gravíssima</span>
    {% endif %}
</li>
<li><strong>Fonte(s): </strong>{{ object.links|join:", "|urlize|url_fix }}</li>
{% endblock %}

{% block extra %}
{% if report.user and report.user == user %}
<div class="divider"></div>

<div class="w-11/12 list-disc list-inside my-1">
    <p>
        <strong>Status: </strong>
        {% if report.status == "AP" %}
        Aprovado &#9989;
        {% elif report.status == "RE" %}
        Recusado &#10060;
        {% else %}
        Aguardando Validação
        {% endif %}
    </p>

    {% if report.status == "RE" %}
    <p><strong>Feedback dos moderadores: </strong>{{ report.feedback }}</p>
    {% endif %}
</div>

{% endif %}
{% endblock %}

infos/templates/report_template.html
{% extends "global/base.html" %}

{% block content %}
<div class="flex flex-column justify-center items-center bg-red-400 text-white w-full h-10 text-center my-6">
    <h1 class="text-2xl font-bold">
        <ion-icon name="megaphone"></ion-icon> Denuncie
    </h1>
</div>

<p>
    {% block errors %}
    {% endblock %}
</p>
<div class="flex flex-col justify-start">
    {% block form_content %}
    {% endblock %}
</div>
{% endblock %}