infos/urls.py
from django.urls import path

from . import views

app_name = "infos"
urlpatterns = [
    path("report/confirmation/", views.ReportSucessView.as_view(), name="success"),
    path("report/", views.ReportFormView.as_view(), name="report"),
    path("denuncia/<int:pk>", views.ReportStrategy.as_view(), name="reportdetail"),
    path("noticia/<int:pk>", views.NewsStrategy.as_view(), name="newsdetail"),
    path("processo/<int:pk>", views.LawsuitStrategy.as_view(), name="lawsuitdetail"),
]

pensenisso/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path
from home.views import HomeView

def about_us(request):
    return render(request, "global/about_us.html")
def privacy_policy(request):
    return render(request, "global/privacy_policy.html")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("about_us", about_us, name="about_us"),
    path("privacy_policy", privacy_policy, name="privacy_policy"),
    path("empresas/", include("company.urls")),
    path("info/", include("infos.urls", namespace="infos")),
    path("users/", include("user.urls", namespace="user")),
    path("search/", include("search.urls", namespace="search")),
    path("comparator/", include("comparator.urls", namespace="comparator")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    ChangePassword,
    EditProfile,
    ListaUsuarios,
    PendingReportList,
    Register,
    ReportValidation,
    UserPage,
    account_redirect,
    CompanyValidation,
    PendingSuggestionList
)

app_name = "user"

urlpatterns = [
    path("", Register.as_view(), name="register"),
    path("profile/<int:pk>", UserPage.as_view(), name="profile"),
    path("usuarios/", ListaUsuarios.as_view(), name="listausuario"),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="logout.html"), name="logout"),
    path(
        "moderation/pending_reports/",
        PendingReportList.as_view(),
        name="pendingreports",
    ),
    path(
        "moderation/pending_reports/<int:pk>",
        ReportValidation.as_view(),
        name="reportvalidation",
    ),
    path(
        "profile/<int:pk>/edit/password",
        ChangePassword.as_view(),
        name="changepassword",
    ),
    path("profile/<int:pk>/edit/", EditProfile.as_view(), name="editprofile"),
    path("profile", account_redirect, name="account-redirect"),
    path(
        "moderation/pending_suggestions/",
        PendingSuggestionList.as_view(),
        name="pendingsuggestions",
    ),
    path(
        "moderation/pending_suggestions/<int:pk>",
        CompanyValidation.as_view(),
        name="suggestionvalidation",
    ),
]

home/views.py
from typing import Any

from django.views.generic import TemplateView

from infos.models import News


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs: Any) -> "dict[str, Any]":
        context = super().get_context_data(**kwargs)
        context.update({"recent_news": News.objects.all().order_by("-date")[:5]})
        return context

home/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" data-theme="light">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pense Nisso</title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.4.19/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.13.2/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
    <link rel="stylesheet" href="{% static 'css/carousel.css' %}">
</head>

<body style="background: linear-gradient(180deg, rgba(34, 81, 202, 0.20) 0%, rgba(34, 81, 202, 0.00) 73.96%);">
    {% include "global/header.html" %}
    <main class="min-h-screen max-w-2xl xl:max-w-4xl flex flex-col justify-center items-center mx-auto space-y-16">
        <!-- Logo do Pense Nisso -->
        <section class="w-full flex flex-row space-x-5 justify-center items-center mt-10">
            <img class="w-36 h-36" src="{% static 'images/pensenisso.png' %}">
            <h1 class="text-6xl font-bold" style="text-shadow: 0px 5px 5px rgba(0, 0, 0, 0.35)">Pense<br>Nisso</h1>
        </section>

        {% include "global/searchbar.html" %}

        <!-- Carrossel de Notícias -->
        <section class="w-10/12 h-full xl:w-7/12">
            <h2 class="text-xl font-bold mb-1.5">Últimas Notícias:</h2>
            <div class="w-full relative m-auto">
                <div class="carousel carousel-center w-full p-4 space-x-4 rounded-box">
                    {% for news in recent_news %}
                    <div class="carousel-item relative w-10/12 h-52 xl:w-3/4 xl:h-64">
                        <a href="{% url 'infos:newsdetail' news.id %}" class="w-full h-full">
                            <img src="{{ news.image.url }}" class="object-cover w-full h-full">
                            <div
                                class="absolute bottom-0 w-full p-2 bg-neutral-700 bg-opacity-70 text-center text-white">
                                <p class="font-bold leading-tight text-justify hyphens-auto text-sm xl:text-normal"
                                    lang="pt-br">
                                    {{ news.title }}
                                </p>
                                <p class="text-opacity-75 text-xs mt-1 xl:text-sm xl:my-1">Leia e saiba mais!</p>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>

                <a class="prev" onclick='plusSlides(-1)'>&#10094;</a>
                <a class="next" onclick='plusSlides(1)'>&#10095;</a>
            </div>

            <div class="text-center">
                {% for news in recent_news %}
                <span class="dot" onclick="currentSlide({{ forloop.counter }})"></span>
                {% endfor %}
            </div>
        </section>
    </main>

    {% include "global/footer.html" %}

    <script src="{% static 'js/carousel.js' %}"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>

</html>