company/urls.py
from django.urls import path

from .views import (
    CompanyFormView,
    CompanyView,
    LawsuitsList,
    NewsList,
    ReportsList,
    change_rate,
    favorite_company,
    SuggestionSucessView,
)

app_name = "company"
urlpatterns = [
    path("<int:pk>/", CompanyView.as_view(), name="company"),
    path("<int:company_id>/change", change_rate, name="change"),
    path("<int:company_id>/favoritar", favorite_company, name="favorite"),
    path("<int:company_id>/noticias", NewsList.as_view(), name="news"),
    path("<int:company_id>/processos", LawsuitsList.as_view(), name="lawsuits"),
    path("<int:company_id>/denuncias", ReportsList.as_view(), name="reports"),
    path("suggest", CompanyFormView.as_view(), name="suggest"),
    path(
        "suggest/confirmation", SuggestionSucessView.as_view(), name="suggest_success"
    ),
]

infos/urls.py
from django.urls import path

from . import views

app_name = "infos"
urlpatterns = [
    path("report/confirmation/", views.ReportSucessView.as_view(), name="success"),
    path("report/", views.ReportFormView.as_view(), name="report"),
    path("denuncia/<int:pk>", views.ReportStrategy.as_view(), name="reportdetail"),
    path("noticia/<int:pk>", views.NewsStrategy.as_view(), name="newsdetail"),
    path("processo/<int:pk>", views.LawsuitStrategy.as_view(), name="lawsuitdetail"),
]

pensenisso/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path
from home.views import HomeView

def about_us(request):
    return render(request, "global/about_us.html")
def privacy_policy(request):
    return render(request, "global/privacy_policy.html")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("about_us", about_us, name="about_us"),
    path("privacy_policy", privacy_policy, name="privacy_policy"),
    path("empresas/", include("company.urls")),
    path("info/", include("infos.urls", namespace="infos")),
    path("users/", include("user.urls", namespace="user")),
    path("search/", include("search.urls", namespace="search")),
    path("comparator/", include("comparator.urls", namespace="comparator")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    ChangePassword,
    EditProfile,
    ListaUsuarios,
    PendingReportList,
    Register,
    ReportValidation,
    UserPage,
    account_redirect,
    CompanyValidation,
    PendingSuggestionList
)

app_name = "user"

urlpatterns = [
    path("", Register.as_view(), name="register"),
    path("profile/<int:pk>", UserPage.as_view(), name="profile"),
    path("usuarios/", ListaUsuarios.as_view(), name="listausuario"),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="logout.html"), name="logout"),
    path(
        "moderation/pending_reports/",
        PendingReportList.as_view(),
        name="pendingreports",
    ),
    path(
        "moderation/pending_reports/<int:pk>",
        ReportValidation.as_view(),
        name="reportvalidation",
    ),
    path(
        "profile/<int:pk>/edit/password",
        ChangePassword.as_view(),
        name="changepassword",
    ),
    path("profile/<int:pk>/edit/", EditProfile.as_view(), name="editprofile"),
    path("profile", account_redirect, name="account-redirect"),
    path(
        "moderation/pending_suggestions/",
        PendingSuggestionList.as_view(),
        name="pendingsuggestions",
    ),
    path(
        "moderation/pending_suggestions/<int:pk>",
        CompanyValidation.as_view(),
        name="suggestionvalidation",
    ),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    favorite_companies = models.ManyToManyField(
        "company.Company", related_name="favorites", blank=True
    )

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


class CreateUserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class ValidateReportForm(forms.Form):
    gravity = forms.ChoiceField(
        choices=(("1", "Leve"), ("2", "Moderada"), ("3", "Grave"), ("4", "Gravíssima")),
        label="Gravidade:",
    )
    action = forms.ChoiceField(
        choices=(("1", "Aprovar"), ("0", "Recusar")),
        label="Ação:",
        widget=forms.RadioSelect,
    )
    feedback = forms.CharField(
        label="Feedback:", widget=forms.Textarea(attrs={"cols": "45", "rows": "8"})
    )

    class Meta:
        fields = ("gravity", "action", "feedback")


class ValidateSuggestionForm(forms.Form):
    action = forms.ChoiceField(
        choices=(("1", "Aprovar"), ("0", "Recusar")),
        label="Ação:",
        widget=forms.RadioSelect,
    )
    name = forms.CharField(label="Nome da Empresa (se aprovada):", max_length=100)
    description = forms.CharField(
        label="Descrição da Empresa (se aprovada):",
        widget=forms.Textarea(attrs={"cols": "45", "rows": "8"}),
    )
    logo = forms.ImageField(
        label="Logo da Empresa (se aprovada):",
        initial="company/logo_not_found.png",
    )

    class Meta:
        fields = ("action", "name", "description", "logo")

user/views.py
from typing import Any

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.contrib.auth.views import PasswordChangeView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, reverse
from django.views.generic import DetailView, FormView, ListView, UpdateView

from company.models import Company, CompanySuggestionModel
from infos.models import Report

from .forms import CreateUserForm, ValidateReportForm, ValidateSuggestionForm
from .models import User


class Register(FormView):
    template_name = "register.html"
    form_class = CreateUserForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("user:login")


class UserPage(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    template_name = "profile.html"
    model = User

    def test_func(self) -> "bool | None":
        return self.request.get_full_path().split("/")[3] == str(self.request.user.id)


class ListaUsuarios(LoginRequiredMixin, ListView):
    template_name = "listausuarios.html"
    model = User


class PendingReportList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = "report_list.html"
    model = Report
    permission_required = "infos.change_report"

    def get_context_data(self, **kwargs: Any) -> "dict[str, Any]":
        context = super().get_context_data(**kwargs)
        context["report_list"] = Report.objects.filter(status="NV")
        return context


class ReportValidation(
    LoginRequiredMixin, PermissionRequiredMixin, FormView, DetailView
):
    template_name = "report_validation.html"
    model = Report
    form_class = ValidateReportForm
    permission_required = "infos.change_report"

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_success_url(self) -> str:
        return reverse("user:pendingreports")

    def get_context_data(self, **kwargs: Any) -> "dict[str, Any]":
        context = super().get_context_data(**kwargs)
        context["report"].links = context.get("report").links.split("\r\n")
        return context

    def form_valid(self, form: Any) -> HttpResponse:
        data = form.cleaned_data
        report = self.get_object()
        report.gravity = data.get("gravity")
        if data.get("action") == "1":
            report.status = "AP"
        else:
            report.status = "RE"
        report.feedback = data.get("feedback")
        report.save(update_fields=["status", "gravity", "feedback"])
        return super().form_valid(form)


class EditProfile(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "edit_profile.html"
    model = User
    fields = ["first_name", "last_name", "username", "email"]

    def test_func(self) -> "bool | None":
        return self.request.get_full_path().split("/")[3] == str(self.request.user.id)

    def get_success_url(self) -> str:
        return reverse("user:profile", args=[self.request.user.id])


class ChangePassword(LoginRequiredMixin, UserPassesTestMixin, PasswordChangeView):
    template_name = "password_change.html"

    def test_func(self) -> "bool | None":
        return self.request.get_full_path().split("/")[3] == str(self.request.user.id)

    def get_success_url(self) -> str:
        return reverse("user:login")


class PendingSuggestionList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = "suggestion_list.html"
    model = CompanySuggestionModel
    permission_required = "company.add_company"

    def get_context_data(self, **kwargs: Any) -> "dict[str, Any]":
        context = super().get_context_data(**kwargs)
        context["suggestion_list"] = CompanySuggestionModel.objects.filter(status="NV")
        return context


class CompanyValidation(
    LoginRequiredMixin, PermissionRequiredMixin, FormView, DetailView
):
    template_name = "company_validation.html"
    model = CompanySuggestionModel
    form_class = ValidateSuggestionForm
    permission_required = "company.add_company"

    def get_initial(self) -> "dict[str, Any]":
        initial = super().get_initial()
        suggestion = self.get_object()
        initial.update({"name": suggestion.name, "description": suggestion.description})
        return initial

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_success_url(self) -> str:
        return reverse("user:pendingsuggestions")

    def form_valid(self, form: Any) -> HttpResponse:
        data = form.cleaned_data
        suggestion = self.get_object()
        if data.get("action") == "1":
            suggestion.status = "AP"

            company = Company(
                name=data.get("name"),
                description=data.get("description"),
                logo=data.get("logo"),
            )
            company.save()
        else:
            suggestion.status = "RE"
        suggestion.save(update_fields=["status"])
        return super().form_valid(form)


@login_required
def account_redirect(request):
    return redirect("user:profile", pk=request.user.pk)

user/templates/company_validation.html
{% extends "global/base.html" %}
{% load info_extras %}
{% load crispy_forms_tags %}

{% block title %}
- Moderação
{% endblock %}

{% block content %}
<div class="w-full text-justify space-y-1 mt-4">
    <h2 class="text-2xl font-bold">{{ object.name }}</h2>
    <p><strong>Área de atuação: </strong>{{ object.field_of_operation }}</p>
    <p><strong>Site da empresa: </strong>{{ object.link|urlize|url_fix }}</p>
    <p><strong>Descrição: </strong>{{ object.description }}</p>
</div>

<div class="divider"></div>

<form enctype="multipart/form-data" method="post" class="flex flex-col mb-6">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Avaliar Sugestão"
        class="bg-blue-700 bg-opacity-30 w-full py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035] mt-2">
</form>
{% endblock %}

user/templates/edit_profile.html
{% extends "global/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
- Editar Perfil
{% endblock %}

{% block content %}
<div class="bg-blue-600 text-white w-full text-center my-6 py-1">
    <h1 class="text-2xl font-bold">Perfil de Usuário</h1>
</div>

<form method="post">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="text-xl mb-6 border-b-2 border-black w-full text-center">
            Altere os campos abaixo para editar seu perfil
        </legend>
        {{ form|crispy }}
    </fieldset>
    <div class="flex flex-nowrap justify-center space-x-10 mt-2 w-full">
        <button type="button" onclick="window.location.href='{% url 'user:profile' request.user.id %}'"
            class="bg-blue-700 bg-opacity-30 w-1/3 py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035]">
            Voltar
        </button>
        <button type="submit"
            class="bg-blue-700 bg-opacity-30 w-2/3 py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035]">
            Alterar Perfil
        </button>
    </div>
</form>
<small class="mt-6">
    Quer mudar sua senha?
    <a href="{% url 'user:changepassword' request.user.id %}" class="underline text-blue-500">Clique aqui</a>
</small>
{% endblock %}

user/templates/listausuarios.html
{% extends "global/base.html" %}

{% block title %}
- Lista de Usuários
{% endblock %}

{% block content %}
<h1>Lista de Usuários Cadastrados</h1>
{% for usuario in object_list %}
<a href="{% url 'user:profile' usuario.pk %}">
    <h2>Usuário {{ usuario.pk }}</h2>
</a>
<p><strong>First Name: </strong>{{ usuario.firstname }}</p>
<p><strong>Last Name: </strong>{{ usuario.lastname }}</p>
<p><strong>Username: </strong>{{ usuario.username }}</p>
<p><strong>Email: </strong>{{ usuario.email }}</p>
{% endfor %}
{% endblock %}

user/templates/login.html
{% extends "global/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
- Fazer Login
{% endblock %}

{% block content %}
<div class="min-h-screen absolute bottom-0 flex justify-center items-center">
    <div class="h-full text-center flex items-center flex-col self-center">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="text-xl mb-6 border-b-2 border-black w-full text-center">
                    Faça Login para continuar
                </legend>
                {{ form|crispy }}
            </fieldset>
            <input type="submit" value="Fazer Login"
                class="bg-blue-700 bg-opacity-30 w-full py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035] mt-2">
        </form>
        <small class="mt-4">
            Não tem uma conta ainda?
            <p>
                <a href="{% url 'user:register' %}" class="underline text-blue-500">Clique aqui para criar uma conta</a>
            </p>
        </small>
    </div>
</div>
{% endblock %}

user/templates/logout.html
{% extends "global/base.html" %}

{% block title %}
- Logout
{% endblock %}

{% block content %}
<div class="min-h-screen absolute bottom-0 flex justify-center items-center">
    <div class="h-full flex justify-center items-center">
        <div class="text-center flex items-center flex-col">
            <h2 class="text-2xl">Você saiu da sua conta</h2>
            <div class="flex flex-nowrap justify-center space-x-5 p-12">
                <a href="{% url 'user:login' %}">
                    <button class="bg-blue-700 bg-opacity-30 py-1.5 px-3 font-semibold rounded-md hover:scale-[1.035]">
                        Fazer Login
                    </button>
                </a>
                <a href="{% url 'user:register' %}">
                    <button class="bg-blue-700 bg-opacity-30 py-1.5 px-3 font-semibold rounded-md hover:scale-[1.035]">
                        Criar uma Conta
                    </button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user/templates/password_change.html
{% extends "global/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
- Alterar Senha
{% endblock %}

{% block content %}
<!-- Change Password Form -->
<div class="w-full flex items-center flex-col">
    <div class="bg-blue-600 text-white w-full text-center my-6 py-1">
        <h1 class="text-2xl font-bold">Perfil de Usuário</h1>
    </div>
    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="text-xl mb-6 border-b-2 border-black w-full text-center">
                Edite os campos abaixo para alterar sua senha
            </legend>
            {{ form|crispy }}
        </fieldset>
        <div class="flex flex-nowrap justify-center space-x-10 mt-2 w-full">
            <button type="button" onclick="window.location.href='{% url 'user:profile' request.user.id %}'"
                class="bg-blue-700 bg-opacity-30 w-1/3 py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035]">
                Voltar
            </button>
            <button type="button" onclick="openModal()"
                class="bg-blue-700 bg-opacity-30 w-2/3 py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035]">
                Alterar Senha
            </button>
        </div>

        <!-- Confirmation Popup -->
        <div class="fixed z-10 inset-0 overflow-y-auto hidden" id="confirm-modal">
            <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
                <div class="fixed inset-0 transition-opacity" aria-hidden="true">
                    <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
                </div>
                <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
                <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full"
                    role="dialog" aria-modal="true" aria-labelledby="modal-headline">
                    <div>
                        <div class="mt-3 text-center sm:mt-5">
                            <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-headline">
                                Tem certeza que deseja alterar sua senha?
                            </h3>
                        </div>
                    </div>
                    <div class="mt-5 sm:mt-6 flex flex-row space-x-10">
                        <button
                            class="inline-flex justify-center w-full rounded-md border border-transparent shadow-sm px-4 py-2 bg-blue-700 bg-opacity-30 text-base font-semibold hover:bg-opacity-40 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:text-sm"
                            type="button" onclick="closeModal()">
                            Cancelar
                        </button>
                        <button
                            class="inline-flex justify-center w-full rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-500 text-base font-semibold hover:bg-red-600 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:text-sm"
                            type="submit">
                            Confirmar Alteração
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    function openModal() {
        document.getElementById('confirm-modal').classList.remove('hidden');
    }
    function closeModal() {
        document.getElementById('confirm-modal').classList.add('hidden');
    }
</script>
{% endblock %}

user/templates/profile.html
{% extends "global/base.html" %}

{% load has_group %}

{% block title %}
- Perfil do Usuário
{% endblock %}

{% block content %}
<div class="bg-blue-600 text-white w-full text-center my-6 py-1">
    <h1 class="text-2xl font-bold">Perfil de Usuário</h1>
</div>

<div class="w-11/12 flex flex-col md:flex-row-reverse">

    <div class="w-full md:w-60 flex flex-col space-y-6 justify-center md:justify-start mb-5">
        <a href="{% url 'user:editprofile' request.user.id %}">
            <button class="bg-blue-700 bg-opacity-30 w-full py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035]
                flex flex-row items-center justify-center gap-1">
                <ion-icon name="pencil"></ion-icon> Editar Perfil
            </button>
        </a>
        <a href="{% url 'user:logout' %}">
            <button class="bg-red-700 bg-opacity-30 w-full py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035]
                flex flex-row items-center justify-center gap-1">
                <ion-icon name="log-out"></ion-icon> Sair da Conta
            </button>
        </a>
    </div>

    <div class="w-full flex flex-col space-y-8 justify-start">
        <div>
            <h2 class="text-xl font-bold mb-1.5">Informações do Usuário</h2>
            <ul>
                <li><strong>Nome: </strong>{{ object.first_name }}</li>
                <li><strong>Sobrenome: </strong>{{ object.last_name }}</li>
                <li><strong>Username: </strong>{{ object.username }}</li>
                <li><strong>Email: </strong>{{ object.email }}</li>
            </ul>
        </div>

        {% if request.user|has_group:"Moderator" %}
        <div>
            <h2 class="text-xl font-bold mb-3">Área de Moderador</h2>
            <ul class="w-full flex flex-col max-xl:space-y-6 xl:flex-row xl:justify-between">
                <li>
                    <a href="{% url 'user:pendingreports' %}">
                        <button
                            class="bg-blue-700 bg-opacity-30 py-3 w-fit py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035]">
                            Denúncias Não Verificadas
                        </button>
                    </a>
                </li>
                <li>
                    <a href="{% url 'user:pendingsuggestions' %}">
                        <button
                            class="bg-blue-700 bg-opacity-30 py-3 w-fit py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035]">
                            Sugestões de Empresas Não Verificadas
                        </button>
                    </a>
                </li>
            </ul>
        </div>
        {% endif %}

        <div>
            <h2 class="text-xl font-bold mb-1.5">Empresas favoritas</h2>
            {% if request.user.favorite_companies.count > 0 %}
            <ul>
                {% for company in object.favorite_companies.all %}
                <li><a class="underline text-blue-500 visited:text-purple-600"
                        href="{% url 'company:company' company.pk %}">{{ company.name }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p class="text-sm">Você ainda não favoritou nenhuma empresa.</p>
            {% endif %}
        </div>

        <div>
            <h2 class="text-xl font-bold mb-1.5">Denúncias enviadas</h2>
            {% if request.user.reports_sent.count > 0 %}
            <ul>
                {% for report in object.reports_sent.all %}
                <li><a class="underline text-blue-500 visited:text-purple-600"
                        href="{% url 'infos:reportdetail' report.pk %}">{{ report.title }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p class="text-sm">Você ainda não enviou nenhum denúncia.</p>
            {% endif %}
        </div>

    </div>

</div>
{% endblock %}

user/templates/register.html
{% extends "global/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
- Cadastro
{% endblock %}

{% block content %}
<div class="flex items-center flex-col mt-6">
    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="text-xl mb-6 border-b-2 border-black w-full text-center">
                É novo por aqui? Crie uma conta:
            </legend>
            {{ form|crispy }}
        </fieldset>
        <input type="submit" value="Criar Conta"
            class="bg-blue-700 bg-opacity-30 w-full py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035] mt-2">
    </form>
</div>
{% endblock %}

user/templates/report_list.html
{% extends "global/base.html" %}

{% block title %}
- Moderação
{% endblock %}

{% block content %}
<!-- Page Title -->
<div class="bg-blue-600 text-white w-full text-center my-6 py-1.5">
    <h1 class="text-2xl font-bold">Denúncias Não Verificadas</h1>
</div>

<div class="w-11/12 space-y-5">
    {% for report in report_list %}
    <div class="bg-indigo-100 rounded-xl pt-2 pb-3 px-4 cursor-pointer hover:scale-[1.035]"
        onclick="window.location.href='{% url 'user:reportvalidation' report.id %}'">
        <h2 class="text-lg font-bold">{{ report.title }}</h2>
        <div class="flex flex-row justify-between">
            <p>{{ report.category }}</p>
            <p>{{ report.company }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

user/templates/report_validation.html
{% extends "global/base.html" %}
{% load info_extras %}
{% load crispy_forms_tags %}

{% block title %}
- Moderação
{% endblock %}

{% block content %}
<div class="w-full text-justify space-y-1 mt-4">
    <h2 class="text-2xl font-bold">{{ report.title }}</h2>
    <p><strong>Empresa envolvida: </strong>{{ report.company }}</p>
    <p><strong>Categoria da denúncia: </strong>{{ report.category }}</p>
    <p><strong>Data: </strong>{{ report.date }}</p>
    <p><strong>Descrição da denúncia: </strong>{{ report.content }}</p>
    <p><strong>Links de evidências: </strong>{{ report.links|join:", "|urlize|url_fix }}</p>
</div>

<div class="divider"></div>

<form method="post" class="flex flex-col mb-6">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Enviar feedback"
        class="bg-blue-700 bg-opacity-30 w-full py-1.5 px-3 font-semibold rounded-md cursor-pointer hover:scale-[1.035] mt-2">
</form>
{% endblock %}

user/templates/suggestion_list.html
{% extends "global/base.html" %}

{% block title %}
- Moderação
{% endblock %}

{% block content %}
<!-- Page Title -->
<div class="bg-blue-600 text-white w-full text-center my-6 py-1.5">
    <h1 class="text-2xl font-bold">Sugestões de Empresas Não Verificadas</h1>
</div>

<div class="w-11/12 space-y-5">
    {% for suggestion in suggestion_list %}
    <div class="bg-indigo-100 rounded-xl pt-2 pb-3 px-4 cursor-pointer hover:scale-[1.035]"
        onclick="window.location.href='{% url 'user:suggestionvalidation' suggestion.id %}'">
        <h2 class="text-lg font-bold">{{ suggestion.name }}</h2>
        <div class="flex flex-row justify-between">
            <p>{{ suggestion.field_of_operation }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}