company/urls.py
from django.urls import path

from .views import (
    CompanyFormView,
    CompanyView,
    LawsuitsList,
    NewsList,
    ReportsList,
    change_rate,
    favorite_company,
    SuggestionSucessView,
)

app_name = "company"
urlpatterns = [
    path("<int:pk>/", CompanyView.as_view(), name="company"),
    path("<int:company_id>/change", change_rate, name="change"),
    path("<int:company_id>/favoritar", favorite_company, name="favorite"),
    path("<int:company_id>/noticias", NewsList.as_view(), name="news"),
    path("<int:company_id>/processos", LawsuitsList.as_view(), name="lawsuits"),
    path("<int:company_id>/denuncias", ReportsList.as_view(), name="reports"),
    path("suggest", CompanyFormView.as_view(), name="suggest"),
    path(
        "suggest/confirmation", SuggestionSucessView.as_view(), name="suggest_success"
    ),
]

comparator/urls.py
from django.urls import path

from . import views

app_name = "comparator"
urlpatterns = [
    path("", views.ComparatorView.as_view(), name="comparator"),
    path("delete/", views.delete, name="delete"),
]

infos/urls.py
from django.urls import path

from . import views

app_name = "infos"
urlpatterns = [
    path("report/confirmation/", views.ReportSucessView.as_view(), name="success"),
    path("report/", views.ReportFormView.as_view(), name="report"),
    path("denuncia/<int:pk>", views.ReportStrategy.as_view(), name="reportdetail"),
    path("noticia/<int:pk>", views.NewsStrategy.as_view(), name="newsdetail"),
    path("processo/<int:pk>", views.LawsuitStrategy.as_view(), name="lawsuitdetail"),
]

pensenisso/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path
from home.views import HomeView

def about_us(request):
    return render(request, "global/about_us.html")
def privacy_policy(request):
    return render(request, "global/privacy_policy.html")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("about_us", about_us, name="about_us"),
    path("privacy_policy", privacy_policy, name="privacy_policy"),
    path("empresas/", include("company.urls")),
    path("info/", include("infos.urls", namespace="infos")),
    path("users/", include("user.urls", namespace="user")),
    path("search/", include("search.urls", namespace="search")),
    path("comparator/", include("comparator.urls", namespace="comparator")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    ChangePassword,
    EditProfile,
    ListaUsuarios,
    PendingReportList,
    Register,
    ReportValidation,
    UserPage,
    account_redirect,
    CompanyValidation,
    PendingSuggestionList
)

app_name = "user"

urlpatterns = [
    path("", Register.as_view(), name="register"),
    path("profile/<int:pk>", UserPage.as_view(), name="profile"),
    path("usuarios/", ListaUsuarios.as_view(), name="listausuario"),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="logout.html"), name="logout"),
    path(
        "moderation/pending_reports/",
        PendingReportList.as_view(),
        name="pendingreports",
    ),
    path(
        "moderation/pending_reports/<int:pk>",
        ReportValidation.as_view(),
        name="reportvalidation",
    ),
    path(
        "profile/<int:pk>/edit/password",
        ChangePassword.as_view(),
        name="changepassword",
    ),
    path("profile/<int:pk>/edit/", EditProfile.as_view(), name="editprofile"),
    path("profile", account_redirect, name="account-redirect"),
    path(
        "moderation/pending_suggestions/",
        PendingSuggestionList.as_view(),
        name="pendingsuggestions",
    ),
    path(
        "moderation/pending_suggestions/<int:pk>",
        CompanyValidation.as_view(),
        name="suggestionvalidation",
    ),
]

company/models.py
import math

from django.db import models
from django.utils.timezone import now

from infos.models import Report

class Company(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    logo = models.ImageField(upload_to="company/logo/%y/%m/%d/")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def compute_score(self) -> "float | int":
        reports = self.reports.filter(status="AP")
        sub_score = 0
        self.main_report = None
        greater_report_score = float('-inf')
        for report in reports:
            age = (now().date() - report.date).days / 365
            report_score = math.exp(-2 * age / int(report.gravity))
            if report_score > greater_report_score:
                greater_report_score = report_score
                self.main_report = report
            sub_score += report_score
        score = round(5 - min(sub_score, 5), 2)

        return score if score - int(score) != 0 else int(score)

    def compute_score_users(self) -> "float | str":
        rates = self.user_ratings.all()
        if len(rates) == 0:
            score_users = "--"
        else:
            sub_score_users = 0
            for rate in rates:
                sub_score_users += rate.score
            score_users = round(sub_score_users / len(rates), 2)
        return score_users

    class Meta:
        verbose_name_plural = "Companies"


class CompanySuggestionModel(models.Model):
    name = models.CharField(max_length=100)
    field_of_operation = models.CharField(max_length=50)
    link = models.URLField(max_length=30, null=True)
    description = models.TextField(max_length=400, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        "user.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="suggestions_sent",
    )
    status = models.CharField(
        max_length=20,
        choices=[("RE", "Recusado"), ("NV", "Não verificado"), ("AP", "Aprovado")],
        default="NV",
    )


class Rate(models.Model):
    company = models.ForeignKey(
        "company.Company", on_delete=models.CASCADE, related_name="user_ratings"
    )
    user = models.ForeignKey(
        "user.User", on_delete=models.CASCADE, related_name="rated_companies"
    )
    score = models.IntegerField()

infos/models.py
from django.db import models


class InfoBase(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self) -> str:
        return self.title

    class Meta:
        abstract = True


class Report(InfoBase):
    company = models.ForeignKey(
        "company.Company", on_delete=models.CASCADE, related_name="reports"
    )
    category = models.ForeignKey("ReportCategory", on_delete=models.SET_NULL, null=True)
    links = models.TextField()
    user = models.ForeignKey(
        "user.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports_sent",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=20,
        choices=[("RE", "Recusado"), ("NV", "Não verificado"), ("AP", "Aprovado")],
        default="NV",
    )
    gravity = models.CharField(
        max_length=20,
        choices=[("1", "Leve"), ("2", "Moderada"), ("3", "Grave"), ("4", "Gravíssima")],
        default="1",
    )
    date = models.DateField(default="1970-01-01")
    feedback = models.TextField(blank=True)


class ReportCategory(models.Model):
    name = models.CharField(max_length=100)
    formatted_name = models.CharField(max_length=100, default="Categoria")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Report categories"


class Lawsuit(InfoBase):
    company = models.ForeignKey(
        "company.Company", on_delete=models.CASCADE, related_name="lawsuits"
    )
    source = models.URLField()
    start_year = models.PositiveSmallIntegerField()
    resolution_year = models.PositiveSmallIntegerField(null=True, blank=True)


class News(InfoBase):
    company = models.ForeignKey(
        "company.Company", on_delete=models.CASCADE, related_name="news"
    )
    author = models.CharField(max_length=50)
    date = models.DateField()
    image = models.ImageField(upload_to="news_banners")

    class Meta:
        verbose_name_plural = "News"

company/forms.py
from django import forms


class CompanySuggestion(forms.Form):
    name = forms.CharField(max_length=100, label="Nome da Empresa:", required=True)
    field_of_operation = forms.CharField(
        max_length=50, label="Área de Atuação:", required=True
    )
    link = forms.URLField(max_length=30, required=False)

    description = forms.CharField(
        max_length=400,
        widget=forms.Textarea(),
        label="Descrição sobre a empresa e sua área de atuação:",
        required=False,
    )

infos/forms.py
from django import forms
from django.forms import widgets

from company.models import Company

from .fields import CompanyModelChoiceField, ReportCategoryModelChoiceField
from .models import ReportCategory
import datetime

STRING_COMPANY = "Empresa envolvida:"
STRING_EMPTY_COMPANY = "Selecione uma empresa"
STRING_LINK = "Links de evidências:"
STRING_DESCRIPTION = "Descrição da denúncia:"
STRING_CONTACT = "Podemos entrar em contato para obter mais informações?"
STRING_CATEGORY = "Escolha uma categoria de denúncia"
STRING_EMPTY_CATEGORY = "Selecione uma categoria"
STRING_DATE = "Data da ocorrência:"

def valid_date(value):
    if value > datetime.date.today():
        raise forms.ValidationError("A data não pode ser maior que a data atual!")
    elif value < datetime.date(1970, 1, 1):
        raise forms.ValidationError("A data não pode ser menor que 01/01/1970!")
    return value

class ReportForm(forms.Form):
    template_name = "form/report_form_template.html"

    company = CompanyModelChoiceField(
        queryset=Company.objects.all(),
        label=STRING_COMPANY,
        empty_label=STRING_EMPTY_COMPANY,
    )
    category = ReportCategoryModelChoiceField(
        queryset=ReportCategory.objects.all(),
        label=STRING_CATEGORY,
        empty_label=STRING_EMPTY_CATEGORY,
    )
    link = forms.URLField(label=STRING_LINK)
    description = forms.CharField(
        label=STRING_DESCRIPTION,
        max_length=300,
        widget=forms.Textarea(attrs={"cols": "45", "rows": "8"}),
    )
    date = forms.DateField(
        label=STRING_DATE, widget=widgets.DateInput(attrs={"type": "date"}), validators=[valid_date],
    )
    contact_permission = forms.BooleanField(
        label=STRING_CONTACT, required=False, initial=False
    )

company/views.py
from typing import Any

from django.contrib.auth import get_user
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import DetailView, FormView, ListView, TemplateView

from infos.models import Lawsuit, News, Report

from .forms import CompanySuggestion
from .models import Company, CompanySuggestionModel, Rate 


class CompanyView(DetailView):
    template_name = "companies/company.html"
    model = Company

    def get_context_data(self, **kwargs: Any) -> "dict[str, Any]":
        context = super().get_context_data(**kwargs)
        obj = self.get_object()

        rates = obj.user_ratings.all()
        user_ratings = []
        for rate in rates:
            user_ratings.append(rate.user)

        context["user_ratings"] = user_ratings
        context["score_users"] = obj.compute_score_users()
        context["score"] = obj.compute_score()
        context["main_report"] = obj.main_report
        return context

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        self.object = self.get_object()
        query = self.request.POST.get("rate")
        context = self.get_context_data(**kwargs)
        print(request.user)
        rate = Rate(company=context["company"], user=request.user, score=int(query))

        rate.save()
        return super().render_to_response(self.get_context_data(**kwargs))


def change_rate(request: HttpRequest, company_id: int) -> HttpResponse:
    company = get_object_or_404(Company, pk=company_id)
    rates = company.user_ratings.filter(user=request.user)
    rates.delete()

    return redirect("company:company", pk=company_id)


def favorite_company(request: HttpRequest, company_id: int) -> HttpResponse:
    company = get_object_or_404(Company, pk=company_id)
    if company in request.user.favorite_companies.all():
        request.user.favorite_companies.remove(company)
    else:
        request.user.favorite_companies.add(company)
    return redirect("company:company", pk=company_id)


class InfosList(ListView):
    template_name = "companies/infos.html"
    model = None
    info_type = ""
    redirect_page = ""

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.company = get_object_or_404(Company, pk=kwargs.get("company_id"))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> "dict[str, Any]":
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "company": self.company,
                "info_type": self.info_type,
                "infos": self.model.objects.filter(company=self.company),
                "redirect_page": self.redirect_page,
            }
        )
        return context


class NewsList(InfosList):
    model = News
    info_type = "Notícias"
    redirect_page = "infos:newsdetail"


class ReportsList(InfosList):
    model = Report
    info_type = "Denúncias"
    redirect_page = "infos:reportdetail"

    def get_context_data(self, **kwargs: Any) -> "dict[str, Any]":
        context = super().get_context_data(**kwargs)
        context["infos"] = self.model.objects.filter(company=self.company, status="AP")
        return context


class LawsuitsList(InfosList):
    model = Lawsuit
    info_type = "Processos"
    redirect_page = "infos:lawsuitdetail"


class SuggestionSucessView(TemplateView):
    template_name = "companies/forms/confirmation.html"


class CompanyFormView(FormView):
    form_class = CompanySuggestion
    success_url = "suggest/confirmation"
    template_name = "companies/forms/company_suggestion.html"

    def form_valid(self, form: CompanySuggestion) -> HttpResponse:
        data = form.cleaned_data
        current_user = get_user(self.request)
        suggestion = CompanySuggestionModel(
            name=data["name"],
            field_of_operation=data["field_of_operation"],
            description=data["description"],
            link=data["link"],
            user=current_user if current_user.is_authenticated else None,
        )

        suggestion.save()
        return super().form_valid(form)

infos/views.py
from typing import Any

from django.contrib.auth import get_user
from django.http import HttpResponse
from django.utils import timezone
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import FormView

from . import forms
from .models import Lawsuit, News, Report


class ReportSucessView(TemplateView):
    template_name = "confirmation.html"


class ReportFormView(FormView):
    template_name = "report.html"
    form_class = forms.ReportForm
    success_url = "confirmation/"

    def form_valid(self, form: forms.ReportForm) -> HttpResponse:
        data = form.cleaned_data
        current_date = timezone.now().isoformat(timespec="seconds")
        current_user = get_user(self.request)

        generated_title = (
            f"{current_date}-{data['company'].name}-{data['category'].name}"
        )

        report = Report(
            title=generated_title,
            content=data["description"],
            category=data["category"],
            links=data["link"],
            company=data["company"],
            user=current_user if current_user.is_authenticated else None,
            date=data["date"],
        )

        report.save()
        return super().form_valid(form)


class InfoStrategy(DetailView):
    info_type = ""

    def get_context_data(self, **kwargs: Any) -> "dict[str, Any]":
        context = super().get_context_data(**kwargs)
        context.update(
            {"info_type": self.info_type, "info_title": self.get_info_title()}
        )
        return context

    def get_info_title(self):
        pass


class ReportStrategy(InfoStrategy):
    model = Report
    info_type = "Denúncia"
    template_name = "report_details.html"

    def get_info_title(self):
        return self.get_object().category

    def get_context_data(self, **kwargs: Any) -> "dict[str, Any]":
        context = super().get_context_data(**kwargs)
        context["object"].links = context.get("object").links.split("\r\n")
        return context


class NewsStrategy(InfoStrategy):
    model = News
    info_type = "Notícia"
    template_name = "news_details.html"

    def get_info_title(self):
        return self.get_object().title


class LawsuitStrategy(InfoStrategy):
    model = Lawsuit
    info_type = "Processo"
    template_name = "lawsuit_details.html"

    def get_info_title(self):
        return self.get_object().title

company/templates/companies/company.html
{% extends "global/base.html" %} {% block title %} - Empresa {% endblock %}
{%block content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.js"></script>

<div class="flex flex-column justify-center items-center bg-blue-600 text-white w-full h-10 text-center my-6">
  <h1 class="text-2xl font-bold">{{ company.name }}</h1>
</div>

<div>

  <div class="flex items-center w-full mb-6">

    <div class="flex flex-col items-center gap-4 place-items-center">
      <img class="w-20 h-20" src="{{company.logo.url}}" alt="Logo Empresa" />
      {% if user.is_authenticated %}
        {% if user in company.favorites.all %}
        <a class="btn" href="{% url "company:favorite" company.id%}"><ion-icon class="text-yellow-700" name="star"></ion-icon>Favoritada</a>
        {% else %}
        <a class="btn" href="{% url "company:favorite" company.id%}"><ion-icon class="text-yellow-700" name="star-outline"></ion-icon>Favoritar</a>
        {% endif %} 
      {% else %}
      <a href="{% url 'user:register' %}" class="btn"><ion-icon class="text-yellow-700" name="star-outline"></ion-icon>Favoritar</a>
      {% endif %}
    </div>

    <div class="mx-5 divider divider-horizontal"></div>

    <div class="flex flex-col gap-6 items-center">
      <h2 class="text-xl font-medium">Avaliações</h2>

      <div class="flex flex-col gap-2 md:flex md:flex-row">

        <div class="grid h-20 flex-grow place-items-center">

          <div class="stat-title text-xl">Pense Nisso</div>

          <div class="stat-value text-xl
          {% if score > 3.75 %}
           bg-green-400 
          {% elif score > 2.5 %}
           bg-yellow-400 
          {% else %}
           bg-red-400 
          {% endif %}
          bg-opacity-40 rounded-xl p-2">
            {{score}}/5
          </div>
    
          <p class="flex items-center text-sm text-gray-500 dark:text-gray-400"> Critérios de avaliação <button data-popover-target="popover-description" data-popover-placement="bottom-end" type="button"><svg class="w-4 h-4 ms-2 text-gray-400 hover:text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg><span class="sr-only">Show information</span></button></p>
          
          <div data-popover id="popover-description" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
              
              <div class="p-3 space-y-2">
                  <h3 class="font-semibold text-gray-900 dark:text-white">Critérios de Avaliação</h3>
                  <p>O Pense Nisso e sua equipe de moderação acredita no uso da tecnologia para divulgar informação segura e confiável. Para complementar o alcance e praticidade de nosa plataforma desenvolvemos um sistema de avaliação de empresas próprio baseado em alguns parâmetros de nossa base de dados para melhor atender nossos usuários. </p>
                  <h3 class="font-semibold text-gray-900 dark:text-white">Cálculo da Nota</h3>
                  <p>O cálculo envolvido nesse sistema de notas leva em consideração uma relação exponencial entre a nota e as denúncias que recebemos a todo momento. Levando em conta não somente a quantidade de denúnicas, mas também a gravidade e o tempo desde quando ocorreram.</p>
                  </svg></a>
              </div>

              <div data-popper-arrow></div>
          </div>

        </div>

        <div class="grid h-20 flex-grow place-items-center">  

          <div class="stat-title text-xl">Consumidores</div>

          <div class="stat-value text-xl
          {% if score_users > 3.75 %}
           bg-green-400 
          {% elif score_users > 2.5 %}
           bg-yellow-400 
          {% else %}
           bg-red-400 
          {% endif %}
          bg-opacity-40 rounded-xl p-2">
            {{score_users}}/5
          </div>

        </div>

    </div>
      
    <div class="flex flex-col items-center">
      {% if user.is_authenticated %}
        {% if user in user_ratings %}
          <p>Você já avaliou esta empresa</p>
          <a class="btn bg-blue-700 bg-opacity-20 hover:bg-blue-700 hover:bg-opacity-40" href="{% url "company:change" company.id%}">Mudar Avaliação</a>
        {% else %}
          <form method="post">
            {% csrf_token %}

            <div class="rating rating-sm">
              <input type="radio" name="rate" class="mask mask-star-2 bg-orange-400" value="1"/>
              <input type="radio" name="rate" class="mask mask-star-2 bg-orange-400" value="2" checked />
              <input type="radio" name="rate" class="mask mask-star-2 bg-orange-400" value="3"/>
              <input type="radio" name="rate" class="mask mask-star-2 bg-orange-400" value="4"/>
              <input type="radio" name="rate" class="mask mask-star-2 bg-orange-400" value="5"/>
            </div>
          
            <input type="submit" value="Avaliar" class="btn normal-case bg-blue-700 bg-opacity-20 hover:bg-blue-700 hover:bg-opacity-40">
          </form>
        {% endif %}  
          
      {% endif %}
    </div>

  </div> 
</div>
</div>

<div class="w-10/12 description px-4 py-2 w-80 bg-blue-700 bg-opacity-20 rounded-[10px] my-6">
  <h3 class="flex flex-row items-center gap-2 text-lg font-bold"><ion-icon name="chatbox-ellipses"></ion-icon> Sobre a empresa</h3>
  <p>{{ company.description }}</p>
</div>

<div class="w-10/12 top-report px-4 py-2 w-80 bg-red-200 rounded-[10px] my-6 flex flex-row items-center space-x-2.5 cursor-pointer"
        {% if main_report %}onclick="window.location.href='{% url 'infos:reportdetail' main_report.id %}'{% endif %}">
  <div class="grow w-full">
    <h3 class="flex flex-row items-center gap-2 text-lg font-bold"><ion-icon class="text-red-600" name="alert-circle"></ion-icon> Principal Denuncia</h3>
    {% if main_report %}
    <p>{{ main_report.content|truncatechars:100 }}</p>
    {% else %}
    <p class="text-sm">Essa empresa ainda não tem denúncias!</p>
    {% endif %}
  </div>
  {% if main_report %}
    <ion-icon name="arrow-forward-outline" class="flex-none"></ion-icon>
  {% endif %}
</div>

<div class="w-10/12">
  <ul class="w-full my-8 infos-pages flex flex-row justify-around items-center">
    <li><a href="{% url 'company:reports' company.id %}" class="btn">Denúncias</a></li>
    <li><a href="{% url 'company:lawsuits' company.id %}" class="btn">Processos</a></li>
    <li><a href="{% url 'company:news' company.id %}" class="btn">Notícias</a></li>
  </ul>
</div>

<div class="w-full flex flex-row justify-evenly">
  <button onclick="window.location.href='{% url 'infos:report' %}'"
    class="bg-red-600 bg-opacity-60 w-1/3 py-1.5 px-3 font-bold rounded-md cursor-pointer hover:scale-[1.035] mt-2">
    <ion-icon name="megaphone"></ion-icon> Denunciar
  </button>
  <form class="w-1/3 flex items-center justify-center bg-blue-700 bg-opacity-30 w-1/3 py-1.5 px-3 font-bold rounded-md cursor-pointer hover:scale-[1.035] mt-2" 
        method="post" action="{% url 'comparator:comparator' %}">
    {% csrf_token %}
    <input type="hidden" name="company" value="{{company.name}}">
    <button onclick="window.location.href='{% url 'comparator:comparator' %}'"
    class="self-center">
      <ion-icon name="git-compare"></ion-icon> Compare
    </button>
  </form>
</div>

{% endblock %}

company/templates/companies/infos.html
{% extends "global/base.html" %}

{% block title %}
- {{ info_type }}
{% endblock %}

{% block content %}
<div class="bg-blue-600 text-white w-full text-center my-6">
    <h1 class="text-2xl font-bold">{{ info_type }}</h1>
    <h2 class="text-sm font-semibold">{{ company.name }}</h2>
</div>

<div class="w-11/12 space-y-5 ">
    {% for info in infos %}
    <div class="bg-blue-700 bg-opacity-20 rounded-xl pt-2 pb-3 px-8 flex flex-row items-center space-x-2.5 cursor-pointer hover:scale-[1.035]"
        onclick="window.location.href = '{% url redirect_page info.id %}';">
        <div class="grow w-full">
            {% if info_type == "Denúncias" %}
            <h3 class="text-lg font-bold">{{ info.category }}</h3>
            {% else %}
            <h3 class="text-lg font-bold">{{ info.title }}</h3>
            {% endif %}

            <p class="text-sm text-justify leading-tight break-words">{{ info.content|truncatechars:300 }}</p>

            {% if info_type == "Notícias" %}
            <p class="text-sm text-neutral-600 mt-1">{{ info.date|date:"d/m/Y" }}</p>
            {% endif %}
        </div>

        <ion-icon name="arrow-forward-outline" class="flex-none"></ion-icon>
    </div>
    {% endfor %}
</div>
{% endblock %}